
package forms;

public class backgroundEffects extends javax.swing.JPanel {


    /**
     * Creates new form backgroundEffects
     */
    public backgroundEffects() {
        initComponents();
    }

    public void setTreasure(boolean flag){
        decorTreasure.setVisible(flag);
    }

    public void setPineapple(boolean flag){
        decorPineapple.setVisible(flag);
    }

    public void setSandCastle(boolean flag){
        decorSandCastle.setVisible(flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bubbles1 = new javax.swing.JLabel();
        bubbles2 = new javax.swing.JLabel();
        bubbles3 = new javax.swing.JLabel();
        decorTreasure = new javax.swing.JLabel();
        decorPineapple = new javax.swing.JLabel();
        decorSandCastle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bubbles1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flow.gif"))); // NOI18N
        add(bubbles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, -1, -1));

        bubbles2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flow.gif"))); // NOI18N
        add(bubbles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        bubbles3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flow.gif"))); // NOI18N
        add(bubbles3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        decorTreasure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/treasure.png"))); // NOI18N
        decorTreasure.setText("jLabel1");
        add(decorTreasure, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        decorPineapple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pineappleHouse.png"))); // NOI18N
        decorPineapple.setText("jLabel1");
        add(decorPineapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        decorSandCastle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sandCastle.png"))); // NOI18N
        decorSandCastle.setText("jLabel1");
        add(decorSandCastle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bubbles1;
    private javax.swing.JLabel bubbles2;
    private javax.swing.JLabel bubbles3;
    private javax.swing.JLabel decorPineapple;
    private javax.swing.JLabel decorSandCastle;
    private javax.swing.JLabel decorTreasure;
    // End of variables declaration//GEN-END:variables
}
