
package forms;

import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import java.util.Timer;
import java.util.TimerTask;

import classes.GameInstance;
import classes.SoundManager;
import classes.parentalControls;
import classes.saveManager;

public class loadGameScreen extends javax.swing.JFrame {
    private saveManager manager;
    private parentalControls gameParentControls;
    /**
     * Creates new form mainGameScreen
     */
    public loadGameScreen() {
        initComponents();
        
    }

    public loadGameScreen(saveManager manager) {
        initComponents();
        this.manager = manager;
        this.gameParentControls = manager.PCReader();

        // Fetch menu data from saveManager
        String[] menuData1 = manager.getMenuData(1);
        String[] menuData2 = manager.getMenuData(2);
        String[] menuData3 = manager.getMenuData(3);

        // Set save file names
        if (menuData1 != null) {save1Label.setText(manager.getMenuData(1)[0]);}
        if (menuData2 != null) {save2Label.setText(manager.getMenuData(2)[0]);}
        if (menuData3 != null) {save3Label.setText(manager.getMenuData(3)[0]);}
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escapePressed");
        this.getRootPane().getActionMap().put("escapePressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                exitMainMenuMouseClicked(null);
            }
        });

        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_1, 0), "save1Pressed");
        this.getRootPane().getActionMap().put("save1Pressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                save1ButtonMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_2, 0), "save2Pressed");
        this.getRootPane().getActionMap().put("save2Pressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                save2ButtonMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_3, 0), "save3Pressed");
        this.getRootPane().getActionMap().put("save3Pressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                save3ButtonMouseClicked(null);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border = new javax.swing.JPanel();
        chooseLoadStateLabel = new javax.swing.JLabel();
        exitFrame = new javax.swing.JPanel();
        exitMainMenu = new javax.swing.JLabel();
        save1Button = new javax.swing.JPanel();
        save1Label = new javax.swing.JLabel();
        save2Button = new javax.swing.JPanel();
        save2Label = new javax.swing.JLabel();
        save3Button = new javax.swing.JPanel();
        save3Label = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        border.setBackground(new java.awt.Color(204, 204, 204));
        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        border.setName("border"); // NOI18N
        border.setOpaque(false);

        chooseLoadStateLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        chooseLoadStateLabel.setForeground(new java.awt.Color(255, 255, 255));
        chooseLoadStateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseLoadStateLabel.setText("Please select a game save.");
        chooseLoadStateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chooseLoadStateLabel.setPreferredSize(new java.awt.Dimension(160, 60));

        exitFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        exitFrame.setPreferredSize(new java.awt.Dimension(72, 32));

        exitMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitButton.png"))); // NOI18N
        exitMainMenu.setName("exitMainMenu"); // NOI18N
        exitMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exitFrameLayout = new javax.swing.GroupLayout(exitFrame);
        exitFrame.setLayout(exitFrameLayout);
        exitFrameLayout.setHorizontalGroup(
            exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitMainMenu)
        );
        exitFrameLayout.setVerticalGroup(
            exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitMainMenu)
        );

        save1Button.setBackground(new java.awt.Color(229, 145, 214));
        save1Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        save1Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save1Button.setPreferredSize(new java.awt.Dimension(700, 80));
        save1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save1ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save1ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save1ButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                save1ButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                save1ButtonMouseReleased(evt);
            }
        });

        save1Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        save1Label.setForeground(new java.awt.Color(255, 255, 255));
        save1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save1Label.setText("[1] Empty");
        save1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save1Label.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout save1ButtonLayout = new javax.swing.GroupLayout(save1Button);
        save1Button.setLayout(save1ButtonLayout);
        save1ButtonLayout.setHorizontalGroup(
            save1ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(save1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        save1ButtonLayout.setVerticalGroup(
            save1ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(save1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        save2Button.setBackground(new java.awt.Color(229, 145, 214));
        save2Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        save2Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save2Button.setPreferredSize(new java.awt.Dimension(700, 80));
        save2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save2ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save2ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save2ButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                save2ButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                save2ButtonMouseReleased(evt);
            }
        });

        save2Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        save2Label.setForeground(new java.awt.Color(255, 255, 255));
        save2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save2Label.setText("[2] Empty");
        save2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save2Label.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout save2ButtonLayout = new javax.swing.GroupLayout(save2Button);
        save2Button.setLayout(save2ButtonLayout);
        save2ButtonLayout.setHorizontalGroup(
            save2ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(save2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        save2ButtonLayout.setVerticalGroup(
            save2ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(save2Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        save3Button.setBackground(new java.awt.Color(229, 145, 214));
        save3Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        save3Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save3Button.setPreferredSize(new java.awt.Dimension(700, 80));
        save3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save3ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save3ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save3ButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                save3ButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                save3ButtonMouseReleased(evt);
            }
        });

        save3Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        save3Label.setForeground(new java.awt.Color(255, 255, 255));
        save3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save3Label.setText("[3] Empty");
        save3Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save3Label.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout save3ButtonLayout = new javax.swing.GroupLayout(save3Button);
        save3Button.setLayout(save3ButtonLayout);
        save3ButtonLayout.setHorizontalGroup(
            save3ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(save3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        save3ButtonLayout.setVerticalGroup(
            save3ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(save3Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(chooseLoadStateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                .addGap(0, 297, Short.MAX_VALUE)
                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(save3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(263, 263, 263))
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(borderLayout.createSequentialGroup()
                        .addComponent(chooseLoadStateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(save1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(save2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(save3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        getContentPane().add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.setName("background"); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(112, 33, 98));
        jLabel4.setText("CS 2212B Winter 2025");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1280, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMainMenuMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        mainMenuScreen nextScreen = new mainMenuScreen(manager);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                loadGameScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_exitMainMenuMouseClicked

    private void save1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1ButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        if (gameParentControls.isPlayAllowed() && manager.getSave(1) != null) {
            GameInstance game = manager.getGameInstance(1);
            mainGameScreen nextScreen = new mainGameScreen(manager, game, 1);
            nextScreen.setVisible(true);
            Timer switchTimer = new Timer();
            TimerTask closeCurrent = new TimerTask() {
                @Override
                public void run() {
                    loadGameScreen.this.dispose();
                    switchTimer.cancel();
                }
            };
            switchTimer.schedule(closeCurrent, 3000);
        }
    }//GEN-LAST:event_save1ButtonMouseClicked

    private void save2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2ButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        if (gameParentControls.isPlayAllowed() && manager.getSave(2) != null) {
            GameInstance game = manager.getGameInstance(2);
            mainGameScreen nextScreen = new mainGameScreen(manager, game, 2);
            nextScreen.setVisible(true);
            Timer switchTimer = new Timer();
            TimerTask closeCurrent = new TimerTask() {
                @Override
                public void run() {
                    loadGameScreen.this.dispose();
                    switchTimer.cancel();
                }
            };
            switchTimer.schedule(closeCurrent, 3000);
        }
    }//GEN-LAST:event_save2ButtonMouseClicked

    private void save3ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3ButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        if (gameParentControls.isPlayAllowed() && manager.getSave(3) != null) {
            GameInstance game = manager.getGameInstance(3);
            mainGameScreen nextScreen = new mainGameScreen(manager, game, 3);
            nextScreen.setVisible(true);
            Timer switchTimer = new Timer();
            TimerTask closeCurrent = new TimerTask() {
                @Override
                public void run() {
                    loadGameScreen.this.dispose();
                    switchTimer.cancel();
                }
            };
            switchTimer.schedule(closeCurrent, 3000);
        }
    }//GEN-LAST:event_save3ButtonMouseClicked

    private void save1ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1ButtonMouseEntered
        save1Button.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_save1ButtonMouseEntered

    private void save1ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1ButtonMouseExited
        save1Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_save1ButtonMouseExited

    private void save1ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1ButtonMousePressed
        save1Button.setBackground(new java.awt.Color(179,96,164));
    }//GEN-LAST:event_save1ButtonMousePressed

    private void save1ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1ButtonMouseReleased
        save1Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_save1ButtonMouseReleased

    private void save2ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2ButtonMouseEntered
        save2Button.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_save2ButtonMouseEntered

    private void save2ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2ButtonMouseExited
        save2Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_save2ButtonMouseExited

    private void save2ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2ButtonMousePressed
        save2Button.setBackground(new java.awt.Color(179,96,164));
    }//GEN-LAST:event_save2ButtonMousePressed

    private void save2ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2ButtonMouseReleased
        save2Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_save2ButtonMouseReleased

    private void save3ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3ButtonMouseEntered
        save3Button.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_save3ButtonMouseEntered

    private void save3ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3ButtonMouseExited
        save3Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_save3ButtonMouseExited

    private void save3ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3ButtonMousePressed
        save3Button.setBackground(new java.awt.Color(179,96,164));
    }//GEN-LAST:event_save3ButtonMousePressed

    private void save3ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3ButtonMouseReleased
        save3Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_save3ButtonMouseReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel border;
    private javax.swing.JLabel chooseLoadStateLabel;
    private javax.swing.JPanel exitFrame;
    private javax.swing.JLabel exitMainMenu;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel save1Button;
    private javax.swing.JLabel save1Label;
    private javax.swing.JPanel save2Button;
    private javax.swing.JLabel save2Label;
    private javax.swing.JPanel save3Button;
    private javax.swing.JLabel save3Label;
    // End of variables declaration//GEN-END:variables
}
