
package forms;

import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import java.util.Timer;
import java.util.TimerTask;
import classes.*;


public class mainMenuScreen extends javax.swing.JFrame {
    private saveManager manager;
    /**
     * Creates new form mainGameScreen
     */
    public mainMenuScreen() {
        initComponents();
        
    }
    public mainMenuScreen(saveManager manager) {
        initComponents();
        this.manager = manager;
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escapePressed");
        this.getRootPane().getActionMap().put("escapePressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                exitMainMenuMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_N, 0), "nPressed");
        this.getRootPane().getActionMap().put("nPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                newGameButtonMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_L, 0), "lPressed");
        this.getRootPane().getActionMap().put("lPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadGameButtonMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_T, 0), "tPressed");
        this.getRootPane().getActionMap().put("tPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tutorialButtonMouseClicked(null);
            }
        });

        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_P, 0), "pPressed");
        this.getRootPane().getActionMap().put("pPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                parentalControlsButtonMouseClicked(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border = new javax.swing.JPanel();
        newGameButton = new javax.swing.JPanel();
        newGameLabel = new javax.swing.JLabel();
        exitFrame = new javax.swing.JPanel();
        exitMainMenu = new javax.swing.JLabel();
        loadGameButton = new javax.swing.JPanel();
        loadGameLabel = new javax.swing.JLabel();
        tutorialButton = new javax.swing.JPanel();
        tutorialLabel = new javax.swing.JLabel();
        parentalControlsButton = new javax.swing.JPanel();
        parentalControlsLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        border.setBackground(new java.awt.Color(204, 204, 204));
        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        border.setName("border"); // NOI18N
        border.setOpaque(false);

        newGameButton.setBackground(new java.awt.Color(229, 145, 214));
        newGameButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        newGameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newGameButton.setPreferredSize(new java.awt.Dimension(400, 80));
        newGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newGameButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newGameButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newGameButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newGameButtonMouseReleased(evt);
            }
        });

        newGameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newGameLabel.setForeground(new java.awt.Color(255, 255, 255));
        newGameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newGameLabel.setText("New Game");
        newGameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newGameLabel.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout newGameButtonLayout = new javax.swing.GroupLayout(newGameButton);
        newGameButton.setLayout(newGameButtonLayout);
        newGameButtonLayout.setHorizontalGroup(
            newGameButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newGameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        newGameButtonLayout.setVerticalGroup(
            newGameButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newGameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        exitFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        exitFrame.setPreferredSize(new java.awt.Dimension(72, 32));

        exitMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitButton.png"))); // NOI18N
        exitMainMenu.setName("exitMainMenu"); // NOI18N
        exitMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exitFrameLayout = new javax.swing.GroupLayout(exitFrame);
        exitFrame.setLayout(exitFrameLayout);
        exitFrameLayout.setHorizontalGroup(
            exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitMainMenu)
        );
        exitFrameLayout.setVerticalGroup(
            exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitMainMenu)
        );

        loadGameButton.setBackground(new java.awt.Color(229, 145, 214));
        loadGameButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        loadGameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadGameButton.setPreferredSize(new java.awt.Dimension(400, 80));
        loadGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadGameButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loadGameButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loadGameButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loadGameButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loadGameButtonMouseReleased(evt);
            }
        });

        loadGameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loadGameLabel.setForeground(new java.awt.Color(255, 255, 255));
        loadGameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadGameLabel.setText("Load Game");
        loadGameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loadGameLabel.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout loadGameButtonLayout = new javax.swing.GroupLayout(loadGameButton);
        loadGameButton.setLayout(loadGameButtonLayout);
        loadGameButtonLayout.setHorizontalGroup(
            loadGameButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadGameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        loadGameButtonLayout.setVerticalGroup(
            loadGameButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadGameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        tutorialButton.setBackground(new java.awt.Color(229, 145, 214));
        tutorialButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        tutorialButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutorialButton.setPreferredSize(new java.awt.Dimension(400, 80));
        tutorialButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutorialButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tutorialButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tutorialButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tutorialButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tutorialButtonMouseReleased(evt);
            }
        });

        tutorialLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tutorialLabel.setForeground(new java.awt.Color(255, 255, 255));
        tutorialLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tutorialLabel.setText("Tutorial");
        tutorialLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tutorialLabel.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout tutorialButtonLayout = new javax.swing.GroupLayout(tutorialButton);
        tutorialButton.setLayout(tutorialButtonLayout);
        tutorialButtonLayout.setHorizontalGroup(
            tutorialButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tutorialLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        tutorialButtonLayout.setVerticalGroup(
            tutorialButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tutorialLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        parentalControlsButton.setBackground(new java.awt.Color(229, 145, 214));
        parentalControlsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        parentalControlsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        parentalControlsButton.setPreferredSize(new java.awt.Dimension(400, 80));
        parentalControlsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parentalControlsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                parentalControlsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                parentalControlsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                parentalControlsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                parentalControlsButtonMouseReleased(evt);
            }
        });

        parentalControlsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        parentalControlsLabel.setForeground(new java.awt.Color(255, 255, 255));
        parentalControlsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        parentalControlsLabel.setText("Parental Controls");
        parentalControlsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        parentalControlsLabel.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout parentalControlsButtonLayout = new javax.swing.GroupLayout(parentalControlsButton);
        parentalControlsButton.setLayout(parentalControlsButtonLayout);
        parentalControlsButtonLayout.setHorizontalGroup(
            parentalControlsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentalControlsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        parentalControlsButtonLayout.setVerticalGroup(
            parentalControlsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentalControlsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(112, 33, 98));
        jLabel2.setText("Team 13");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(112, 33, 98));
        jLabel3.setText("Beril Kayla Coban, Cadence Megan McGillicuddy, Emily Fabing");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(112, 33, 98));
        jLabel5.setText("Everett Guyea, Darsh Srikanth");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TITLE-01.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(112, 33, 98));
        jLabel7.setText("CS 2212B Winter");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(112, 33, 98));
        jLabel8.setText("Western University");

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutorialButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentalControlsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(borderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addContainerGap())
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel3)
                        .addContainerGap(264, Short.MAX_VALUE))))
            .addGroup(borderLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(348, 348, 348)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(loadGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tutorialButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(parentalControlsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(95, 95, 95))
        );

        getContentPane().add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.setName("background"); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(112, 33, 98));
        jLabel4.setText("CS 2212B Winter 2025");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1280, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMainMenuMouseClicked
        SoundManager.stopBackgroundMusic();
        System.exit(0);
    }//GEN-LAST:event_exitMainMenuMouseClicked

    private void newGameButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButtonMousePressed
        newGameButton.setBackground(new java.awt.Color(179,96,164));
        //action
    }//GEN-LAST:event_newGameButtonMousePressed

    private void newGameButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButtonMouseReleased
        newGameButton.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_newGameButtonMouseReleased

    private void newGameButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButtonMouseEntered
        newGameButton.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_newGameButtonMouseEntered

    private void newGameButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButtonMouseExited
        newGameButton.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_newGameButtonMouseExited

    private void loadGameButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadGameButtonMouseEntered
        loadGameButton.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_loadGameButtonMouseEntered

    private void loadGameButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadGameButtonMouseExited
        loadGameButton.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_loadGameButtonMouseExited

    private void loadGameButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadGameButtonMousePressed
        loadGameButton.setBackground(new java.awt.Color(179,96,164));
    }//GEN-LAST:event_loadGameButtonMousePressed

    private void loadGameButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadGameButtonMouseReleased
        loadGameButton.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_loadGameButtonMouseReleased

    private void tutorialButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialButtonMouseEntered
        tutorialButton.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_tutorialButtonMouseEntered

    private void tutorialButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialButtonMouseExited
        tutorialButton.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_tutorialButtonMouseExited

    private void tutorialButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialButtonMousePressed
        tutorialButton.setBackground(new java.awt.Color(179,96,164));
    }//GEN-LAST:event_tutorialButtonMousePressed

    private void tutorialButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialButtonMouseReleased
        tutorialButton.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_tutorialButtonMouseReleased

    private void parentalControlsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parentalControlsButtonMouseEntered
        parentalControlsButton.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_parentalControlsButtonMouseEntered

    private void parentalControlsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parentalControlsButtonMouseExited
        parentalControlsButton.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_parentalControlsButtonMouseExited

    private void parentalControlsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parentalControlsButtonMousePressed
        parentalControlsButton.setBackground(new java.awt.Color(179,96,164));
    }//GEN-LAST:event_parentalControlsButtonMousePressed

    private void parentalControlsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parentalControlsButtonMouseReleased
        parentalControlsButton.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_parentalControlsButtonMouseReleased

    private void loadGameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadGameButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        loadGameScreen nextScreen = new loadGameScreen(manager);
        nextScreen.setVisible(true);

        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                mainMenuScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);

    }//GEN-LAST:event_loadGameButtonMouseClicked

    private void parentalControlsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parentalControlsButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        parentalControlsScreen nextScreen = new parentalControlsScreen(manager);
        nextScreen.setVisible(true);

        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                mainMenuScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_parentalControlsButtonMouseClicked

    private void newGameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        newGameGUI nextScreen = new newGameGUI(manager);
        nextScreen.setVisible(true);

        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                mainMenuScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_newGameButtonMouseClicked

    private void tutorialButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        tutorialScreen nextScreen = new tutorialScreen(manager);
        nextScreen.setVisible(true);

        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                mainMenuScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_tutorialButtonMouseClicked

    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel border;
    private javax.swing.JPanel exitFrame;
    private javax.swing.JLabel exitMainMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel loadGameButton;
    private javax.swing.JLabel loadGameLabel;
    private javax.swing.JPanel newGameButton;
    private javax.swing.JLabel newGameLabel;
    private javax.swing.JPanel parentalControlsButton;
    private javax.swing.JLabel parentalControlsLabel;
    private javax.swing.JPanel tutorialButton;
    private javax.swing.JLabel tutorialLabel;
    // End of variables declaration//GEN-END:variables
}
