
package forms;

import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import java.util.Timer;
import java.util.TimerTask;

import classes.SoundManager;
import classes.saveManager;

public class newGameGUI extends javax.swing.JFrame {
    private saveManager manager;
    /**
     * Creates new form mainGameScreen
     */
    public newGameGUI() {
        initComponents();
        
    }

    public newGameGUI(saveManager manager) {
        initComponents();
        this.manager = manager;
        if (manager.getSave(1) != null) {
            gameSlot1Button.setText(manager.getMenuData(1)[0]);
        }
        if (manager.getSave(2) != null) {
            gameSlot2Button.setText(manager.getMenuData(2)[0]);
        }
        if (manager.getSave(3) != null) {
            gameSlot3Button.setText(manager.getMenuData(3)[0]);
        }
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escapePressed");
        this.getRootPane().getActionMap().put("escapePressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                exitMainMenuMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_1, 0), "slot1Pressed");
        this.getRootPane().getActionMap().put("slot1Pressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                slot1ButtonMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_2, 0), "slot2Pressed");
        this.getRootPane().getActionMap().put("slot2Pressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                slot2ButtonMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_3, 0), "slot3Pressed");
        this.getRootPane().getActionMap().put("slot3Pressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                slot3ButtonMouseClicked(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border = new javax.swing.JPanel();
        slot1Button = new javax.swing.JPanel();
        gameSlot1Button = new javax.swing.JLabel();
        newGameTitle = new javax.swing.JPanel();
        newMenuText = new javax.swing.JLabel();
        slot2Button = new javax.swing.JPanel();
        gameSlot2Button = new javax.swing.JLabel();
        slot3Button = new javax.swing.JPanel();
        gameSlot3Button = new javax.swing.JLabel();
        exitFrame = new javax.swing.JPanel();
        exitMainMenu = new javax.swing.JLabel();
        backgroundEffects = new forms.backgroundEffects();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        border.setBackground(new java.awt.Color(204, 204, 204));
        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        border.setName("border"); // NOI18N
        border.setOpaque(false);

        slot1Button.setBackground(new java.awt.Color(229, 145, 214));
        slot1Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        slot1Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slot1Button.setPreferredSize(new java.awt.Dimension(160, 60));
        slot1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slot1ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slot1ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slot1ButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                slot1ButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slot1ButtonMouseReleased(evt);
            }
        });

        gameSlot1Button.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        gameSlot1Button.setForeground(new java.awt.Color(255, 255, 255));
        gameSlot1Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameSlot1Button.setText("[1] New Pet");
        gameSlot1Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gameSlot1Button.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout slot1ButtonLayout = new javax.swing.GroupLayout(slot1Button);
        slot1Button.setLayout(slot1ButtonLayout);
        slot1ButtonLayout.setHorizontalGroup(
            slot1ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot1ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameSlot1Button, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );
        slot1ButtonLayout.setVerticalGroup(
            slot1ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slot1ButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gameSlot1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        newGameTitle.setName(""); // NOI18N
        newGameTitle.setOpaque(false);

        newMenuText.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        newMenuText.setForeground(new java.awt.Color(255, 255, 255));
        newMenuText.setText("New Game");

        javax.swing.GroupLayout newGameTitleLayout = new javax.swing.GroupLayout(newGameTitle);
        newGameTitle.setLayout(newGameTitleLayout);
        newGameTitleLayout.setHorizontalGroup(
            newGameTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newGameTitleLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(newMenuText)
                .addGap(53, 53, 53))
        );
        newGameTitleLayout.setVerticalGroup(
            newGameTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newGameTitleLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(newMenuText)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        slot2Button.setBackground(new java.awt.Color(229, 145, 214));
        slot2Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        slot2Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slot2Button.setPreferredSize(new java.awt.Dimension(160, 60));
        slot2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slot2ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slot2ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slot2ButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                slot2ButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slot2ButtonMouseReleased(evt);
            }
        });

        gameSlot2Button.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        gameSlot2Button.setForeground(new java.awt.Color(255, 255, 255));
        gameSlot2Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameSlot2Button.setText("[2] New Pet");
        gameSlot2Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gameSlot2Button.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout slot2ButtonLayout = new javax.swing.GroupLayout(slot2Button);
        slot2Button.setLayout(slot2ButtonLayout);
        slot2ButtonLayout.setHorizontalGroup(
            slot2ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot2ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameSlot2Button, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );
        slot2ButtonLayout.setVerticalGroup(
            slot2ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slot2ButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gameSlot2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        slot3Button.setBackground(new java.awt.Color(229, 145, 214));
        slot3Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        slot3Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slot3Button.setPreferredSize(new java.awt.Dimension(160, 60));
        slot3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slot3ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slot3ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slot3ButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                slot3ButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slot3ButtonMouseReleased(evt);
            }
        });

        gameSlot3Button.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        gameSlot3Button.setForeground(new java.awt.Color(255, 255, 255));
        gameSlot3Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameSlot3Button.setText("[3] New Pet");
        gameSlot3Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gameSlot3Button.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout slot3ButtonLayout = new javax.swing.GroupLayout(slot3Button);
        slot3Button.setLayout(slot3ButtonLayout);
        slot3ButtonLayout.setHorizontalGroup(
            slot3ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot3ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameSlot3Button, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );
        slot3ButtonLayout.setVerticalGroup(
            slot3ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slot3ButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gameSlot3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        exitFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        exitFrame.setPreferredSize(new java.awt.Dimension(72, 32));

        exitMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitButton.png"))); // NOI18N
        exitMainMenu.setName("exitMainMenu"); // NOI18N
        exitMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exitFrameLayout = new javax.swing.GroupLayout(exitFrame);
        exitFrame.setLayout(exitFrameLayout);
        exitFrameLayout.setHorizontalGroup(
            exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitMainMenu)
        );
        exitFrameLayout.setVerticalGroup(
            exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitMainMenu)
        );

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1168, Short.MAX_VALUE))
            .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borderLayout.createSequentialGroup()
                    .addGap(439, 439, 439)
                    .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newGameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(slot1Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(slot2Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(slot3Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(439, Short.MAX_VALUE)))
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(652, Short.MAX_VALUE))
            .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borderLayout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(newGameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(slot1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addComponent(slot2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addComponent(slot3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        getContentPane().add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
        getContentPane().add(backgroundEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.setName("background"); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMainMenuMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        mainMenuScreen nextScreen = new mainMenuScreen(manager);
        nextScreen.setVisible(true);

        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                newGameGUI.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_exitMainMenuMouseClicked

    private void slot1ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot1ButtonMouseEntered
        slot1Button.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_slot1ButtonMouseEntered

    private void slot1ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot1ButtonMouseExited
        slot1Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_slot1ButtonMouseExited

    private void slot1ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot1ButtonMousePressed
        slot1Button.setBackground(new java.awt.Color(179,96,164));
    }//GEN-LAST:event_slot1ButtonMousePressed

    private void slot1ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot1ButtonMouseReleased
        slot1Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_slot1ButtonMouseReleased

    private void slot2ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot2ButtonMouseEntered
        slot2Button.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_slot2ButtonMouseEntered

    private void slot2ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot2ButtonMouseExited
        slot2Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_slot2ButtonMouseExited

    private void slot2ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot2ButtonMousePressed
        slot2Button.setBackground(new java.awt.Color(179,96,164));
    }//GEN-LAST:event_slot2ButtonMousePressed

    private void slot2ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot2ButtonMouseReleased
        slot2Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_slot2ButtonMouseReleased

    private void slot3ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot3ButtonMouseEntered
        slot3Button.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_slot3ButtonMouseEntered

    private void slot3ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot3ButtonMouseExited
        slot3Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_slot3ButtonMouseExited

    private void slot3ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot3ButtonMousePressed
        slot3Button.setBackground(new java.awt.Color(179,96,164));
    }//GEN-LAST:event_slot3ButtonMousePressed

    private void slot3ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot3ButtonMouseReleased
        slot3Button.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_slot3ButtonMouseReleased

    private void slot1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot1ButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        petTypeScreen nextScreen = new petTypeScreen(manager, 1);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                newGameGUI.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_slot1ButtonMouseClicked

    private void slot2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot2ButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        petTypeScreen nextScreen = new petTypeScreen(manager, 2);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                newGameGUI.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_slot2ButtonMouseClicked

    private void slot3ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot3ButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        petTypeScreen nextScreen = new petTypeScreen(manager, 3);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                newGameGUI.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_slot3ButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private forms.backgroundEffects backgroundEffects;
    private javax.swing.JPanel border;
    private javax.swing.JPanel exitFrame;
    private javax.swing.JLabel exitMainMenu;
    private javax.swing.JLabel gameSlot1Button;
    private javax.swing.JLabel gameSlot2Button;
    private javax.swing.JLabel gameSlot3Button;
    private javax.swing.JPanel newGameTitle;
    private javax.swing.JLabel newMenuText;
    private javax.swing.JPanel slot1Button;
    private javax.swing.JPanel slot2Button;
    private javax.swing.JPanel slot3Button;
    // End of variables declaration//GEN-END:variables
}
