
package forms;

import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import java.util.Timer;
import java.util.TimerTask;

import classes.SoundManager;
import classes.saveManager;
import classes.parentalControls;

public class parentalControlsScreen extends javax.swing.JFrame {
    private saveManager manager;
    private parentalControls gameParentControls;
    /**
     * Creates new form mainGameScreen
     */
    public parentalControlsScreen() {
        initComponents();
        incorrectPassMessage.setVisible(false);
    }

    public parentalControlsScreen(saveManager manager) {
        initComponents();
        this.manager = manager;
        this.gameParentControls = manager.PCReader();
        incorrectPassMessage.setVisible(false);
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escapePressed");
        this.getRootPane().getActionMap().put("escapePressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                exitMainMenuMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enterPressed");
        this.getRootPane().getActionMap().put("enterPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                enterButtonActionPerformed(null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border = new javax.swing.JPanel();
        exitFrame = new javax.swing.JPanel();
        exitMainMenu = new javax.swing.JLabel();
        backPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        parentPasswordField = new javax.swing.JPasswordField();
        enterButton = new javax.swing.JButton();
        incorrectPassMessage = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        border.setBackground(new java.awt.Color(204, 204, 204));
        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        border.setName("border"); // NOI18N
        border.setOpaque(false);

        exitFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        exitFrame.setPreferredSize(new java.awt.Dimension(72, 32));

        exitMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitButton.png"))); // NOI18N
        exitMainMenu.setName("exitMainMenu"); // NOI18N
        exitMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exitFrameLayout = new javax.swing.GroupLayout(exitFrame);
        exitFrame.setLayout(exitFrameLayout);
        exitFrameLayout.setHorizontalGroup(
            exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitMainMenu)
        );
        exitFrameLayout.setVerticalGroup(
            exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitMainMenu)
        );

        backPanel.setBackground(new java.awt.Color(229, 145, 214));
        backPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(179, 96, 164), 4, true));
        backPanel.setPreferredSize(new java.awt.Dimension(1100, 550));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Parental Controls");

        parentPasswordField.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        parentPasswordField.setForeground(new java.awt.Color(229, 145, 214));
        parentPasswordField.setPreferredSize(new java.awt.Dimension(500, 75));

        enterButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterButton.setForeground(new java.awt.Color(229, 145, 214));
        enterButton.setText("Enter");
        enterButton.setPreferredSize(new java.awt.Dimension(200, 50));
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        incorrectPassMessage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        incorrectPassMessage.setForeground(new java.awt.Color(255, 255, 255));
        incorrectPassMessage.setText("Incorrect password. Please try again.");

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(parentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(incorrectPassMessage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(parentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(incorrectPassMessage)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        getContentPane().add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.setName("background"); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1280, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void exitMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMainMenuMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        mainMenuScreen nextScreen = new mainMenuScreen(manager);
        nextScreen.setVisible(true);

        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                parentalControlsScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_exitMainMenuMouseClicked

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        SoundManager.playSound("sound/button_click.wav");
        char[] pf = parentPasswordField.getPassword();
        String value = new String(pf);
        if (value.equals(gameParentControls.getPassword())) {
            parentalControlsHomeScreen nextScreen = new parentalControlsHomeScreen(manager);
            nextScreen.setVisible(true);
            Timer switchTimer = new Timer();
            TimerTask closeCurrent = new TimerTask() {
                @Override
                public void run() {
                    parentalControlsScreen.this.dispose();
                    switchTimer.cancel();
                }
            };
            switchTimer.schedule(closeCurrent, 3000);
        } else {
            incorrectPassMessage.setVisible(true);
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel background;
    private javax.swing.JPanel border;
    private javax.swing.JButton enterButton;
    private javax.swing.JPanel exitFrame;
    private javax.swing.JLabel exitMainMenu;
    private javax.swing.JLabel incorrectPassMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField parentPasswordField;
    // End of variables declaration//GEN-END:variables
}
