
package forms;

import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import java.util.Timer;
import java.util.TimerTask;

import classes.*;


public class petNameScreen extends javax.swing.JFrame {
    private String selectedPet;
    private saveManager manager;
    private int saveSlot;
    /**
     * Creates new form mainGameScreen
     */
    public petNameScreen() {
        initComponents();
        
    }
    
    
    public petNameScreen(saveManager manager, String selectedPet, int saveSlot) {
        initComponents();
        this.selectedPet = selectedPet;
        this.manager = manager;
        this.saveSlot = saveSlot;
        displayPetImage();
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escapePressed");
        this.getRootPane().getActionMap().put("escapePressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                exitMainMenuMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "newGamePressed");
        this.getRootPane().getActionMap().put("newGamePressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                newGameButtonMouseClicked(null);
            }
        });
        
    }
    
        // method to switch between displayed pet given choice made on selectPetType
    private void displayPetImage() {
    switch (selectedPet) {
        case "pufferfish" -> petImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pufferfishPreview.png")));
        case "axolotl" -> petImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/axolotlPreview.png")));
        case "shark" -> petImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sharkPreview.png")));
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border = new javax.swing.JPanel();
        exitFrame = new javax.swing.JPanel();
        exitMainMenu = new javax.swing.JLabel();
        namePetText = new javax.swing.JLabel();
        petImagePanel = new javax.swing.JPanel();
        petImage = new javax.swing.JLabel();
        petNameInput = new javax.swing.JTextField();
        newGameButton = new javax.swing.JPanel();
        newGameLabel = new javax.swing.JLabel();
        backgroundEffects = new forms.backgroundEffects();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        border.setBackground(new java.awt.Color(204, 204, 204));
        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        border.setName("border"); // NOI18N
        border.setOpaque(false);

        exitFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        exitFrame.setPreferredSize(new java.awt.Dimension(72, 32));

        exitMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitButton.png"))); // NOI18N
        exitMainMenu.setName("exitMainMenu"); // NOI18N
        exitMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exitFrameLayout = new javax.swing.GroupLayout(exitFrame);
        exitFrame.setLayout(exitFrameLayout);
        exitFrameLayout.setHorizontalGroup(
            exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitMainMenu)
        );
        exitFrameLayout.setVerticalGroup(
            exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitMainMenu)
        );

        namePetText.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        namePetText.setForeground(new java.awt.Color(255, 255, 255));
        namePetText.setText("Name Pet");

        petImagePanel.setOpaque(false);

        javax.swing.GroupLayout petImagePanelLayout = new javax.swing.GroupLayout(petImagePanel);
        petImagePanel.setLayout(petImagePanelLayout);
        petImagePanelLayout.setHorizontalGroup(
            petImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(petImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
        petImagePanelLayout.setVerticalGroup(
            petImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(petImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        petNameInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        petNameInput.setForeground(new java.awt.Color(229, 145, 214));
        petNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petNameInputActionPerformed(evt);
            }
        });

        newGameButton.setBackground(new java.awt.Color(229, 145, 214));
        newGameButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        newGameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newGameButton.setPreferredSize(new java.awt.Dimension(160, 60));
        newGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newGameButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newGameButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newGameButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newGameButtonMouseReleased(evt);
            }
        });

        newGameLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        newGameLabel.setForeground(new java.awt.Color(255, 255, 255));
        newGameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newGameLabel.setText("New Game!");
        newGameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newGameLabel.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout newGameButtonLayout = new javax.swing.GroupLayout(newGameButton);
        newGameButton.setLayout(newGameButtonLayout);
        newGameButtonLayout.setHorizontalGroup(
            newGameButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newGameButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newGameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );
        newGameButtonLayout.setVerticalGroup(
            newGameButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newGameButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(newGameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(413, 413, 413)
                        .addComponent(namePetText))
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(petImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(petNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(borderLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(namePetText)))
                .addGap(18, 18, 18)
                .addComponent(petImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(petNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
        getContentPane().add(backgroundEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.setName("background"); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMainMenuMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        petPreviewScreen nextScreen = new petPreviewScreen(manager, selectedPet, saveSlot);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                petNameScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_exitMainMenuMouseClicked

    private void petNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petNameInputActionPerformed

    }//GEN-LAST:event_petNameInputActionPerformed

    private void newGameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButtonMouseClicked
        int petType = 0;

        SoundManager.playSound("sound/button_click.wav");
        String petName = petNameInput.getText().trim();
        if (selectedPet.equals("shark")) {
            petType = 0;
        } else if (selectedPet.equals("pufferfish")) {
            petType = 1;
        } else if (selectedPet.equals("axolotl")) {
            petType = 2;
        }
        save newSave = new save(petName, petType,100,100,100,100,0,100, new int[]{1,1,1}, new int[]{1,1,1}, new boolean[][]{{false,false},{false,false},{false,false}});
        manager.setSave(saveSlot, newSave);

        SoundManager.playSound("sound/button_click.wav");
        mainMenuScreen nextScreen = new mainMenuScreen(manager);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                petNameScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_newGameButtonMouseClicked

    private void newGameButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButtonMouseEntered
        newGameButton.setBackground(new java.awt.Color(241,179,230));
    }//GEN-LAST:event_newGameButtonMouseEntered

    private void newGameButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButtonMouseExited
        newGameButton.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_newGameButtonMouseExited

    private void newGameButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButtonMousePressed
        newGameButton.setBackground(new java.awt.Color(179,96,164));
    }//GEN-LAST:event_newGameButtonMousePressed

    private void newGameButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButtonMouseReleased
        newGameButton.setBackground(new java.awt.Color(229,145,214));
    }//GEN-LAST:event_newGameButtonMouseReleased



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private forms.backgroundEffects backgroundEffects;
    private javax.swing.JPanel border;
    private javax.swing.JPanel exitFrame;
    private javax.swing.JLabel exitMainMenu;
    private javax.swing.JLabel namePetText;
    private javax.swing.JPanel newGameButton;
    private javax.swing.JLabel newGameLabel;
    private javax.swing.JLabel petImage;
    private javax.swing.JPanel petImagePanel;
    private javax.swing.JTextField petNameInput;
    // End of variables declaration//GEN-END:variables
}
