
package forms;

import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import java.util.Timer;
import java.util.TimerTask;

import classes.SoundManager;
import classes.saveManager;
import classes.parentalControls;

public class petRevivalScreen extends javax.swing.JFrame {
    private saveManager manager;
    private parentalControls gameParentControls;
    /**
     * Creates new form mainGameScreen
     */
    public petRevivalScreen() {
        initComponents();
        reviveSuccessfulLabel.setVisible(false);
    }

    public petRevivalScreen(saveManager manager) {
        initComponents();
        this.manager = manager;
        this.gameParentControls = manager.PCReader();
        reviveSuccessfulLabel.setVisible(false);

        // Fetch menu data from saveManager
        String[] menuData1 = manager.getMenuData(1);
        String[] menuData2 = manager.getMenuData(2);
        String[] menuData3 = manager.getMenuData(3);

        // Set save file names
        if (menuData1 != null) {gameSave1Label.setText(manager.getMenuData(1)[0]);}
        if (menuData2 != null) {gameSave2Label.setText(manager.getMenuData(2)[0]);}
        if (menuData3 != null) {gameSave3Label.setText(manager.getMenuData(3)[0]);}
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escapePressed");
        this.getRootPane().getActionMap().put("escapePressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                backButtonMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_1, 0), "save1Pressed");
        this.getRootPane().getActionMap().put("save1Pressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                gameSave1ButtonMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_2, 0), "save2Pressed");
        this.getRootPane().getActionMap().put("save2Pressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                gameSave2ButtonMouseClicked(null);
            }
        });
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_3, 0), "save3Pressed");
        this.getRootPane().getActionMap().put("save3Pressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                gameSave3ButtonMouseClicked(null);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border = new javax.swing.JPanel();
        backPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JPanel();
        backButtonLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gameSave1Button = new javax.swing.JPanel();
        gameSave1Label = new javax.swing.JLabel();
        gameSave2Button = new javax.swing.JPanel();
        gameSave2Label = new javax.swing.JLabel();
        gameSave3Button = new javax.swing.JPanel();
        gameSave3Label = new javax.swing.JLabel();
        reviveSuccessfulLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        border.setBackground(new java.awt.Color(204, 204, 204));
        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        border.setName("border"); // NOI18N
        border.setOpaque(false);

        backPanel.setBackground(new java.awt.Color(229, 145, 214));
        backPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(179, 96, 164), 4, true));
        backPanel.setPreferredSize(new java.awt.Dimension(1100, 550));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pet Revival");

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setForeground(new java.awt.Color(229, 145, 214));
        backButton.setPreferredSize(new java.awt.Dimension(220, 47));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        backButtonLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backButtonLabel.setForeground(new java.awt.Color(229, 145, 214));
        backButtonLabel.setText("Back");

        javax.swing.GroupLayout backButtonLayout = new javax.swing.GroupLayout(backButton);
        backButton.setLayout(backButtonLayout);
        backButtonLayout.setHorizontalGroup(
            backButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(backButtonLabel)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        backButtonLayout.setVerticalGroup(
            backButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(backButtonLabel)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please select the save slot which contains the pet you would like to revive.");

        gameSave1Button.setBackground(new java.awt.Color(255, 255, 255));
        gameSave1Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gameSave1Button.setPreferredSize(new java.awt.Dimension(500, 50));
        gameSave1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameSave1ButtonMouseClicked(evt);
            }
        });

        gameSave1Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gameSave1Label.setForeground(new java.awt.Color(229, 145, 214));
        gameSave1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameSave1Label.setText("[1] Empty");
        gameSave1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gameSave1Label.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout gameSave1ButtonLayout = new javax.swing.GroupLayout(gameSave1Button);
        gameSave1Button.setLayout(gameSave1ButtonLayout);
        gameSave1ButtonLayout.setHorizontalGroup(
            gameSave1ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameSave1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        gameSave1ButtonLayout.setVerticalGroup(
            gameSave1ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameSave1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        gameSave2Button.setBackground(new java.awt.Color(255, 255, 255));
        gameSave2Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gameSave2Button.setPreferredSize(new java.awt.Dimension(500, 50));
        gameSave2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameSave2ButtonMouseClicked(evt);
            }
        });

        gameSave2Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gameSave2Label.setForeground(new java.awt.Color(229, 145, 214));
        gameSave2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameSave2Label.setText("[2] Empty");
        gameSave2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gameSave2Label.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout gameSave2ButtonLayout = new javax.swing.GroupLayout(gameSave2Button);
        gameSave2Button.setLayout(gameSave2ButtonLayout);
        gameSave2ButtonLayout.setHorizontalGroup(
            gameSave2ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameSave2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        gameSave2ButtonLayout.setVerticalGroup(
            gameSave2ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameSave2Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        gameSave3Button.setBackground(new java.awt.Color(255, 255, 255));
        gameSave3Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gameSave3Button.setPreferredSize(new java.awt.Dimension(500, 50));
        gameSave3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameSave3ButtonMouseClicked(evt);
            }
        });

        gameSave3Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gameSave3Label.setForeground(new java.awt.Color(229, 145, 214));
        gameSave3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameSave3Label.setText("[3] Empty");
        gameSave3Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gameSave3Label.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout gameSave3ButtonLayout = new javax.swing.GroupLayout(gameSave3Button);
        gameSave3Button.setLayout(gameSave3ButtonLayout);
        gameSave3ButtonLayout.setHorizontalGroup(
            gameSave3ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameSave3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        gameSave3ButtonLayout.setVerticalGroup(
            gameSave3ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameSave3Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        reviveSuccessfulLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reviveSuccessfulLabel.setForeground(new java.awt.Color(255, 255, 255));
        reviveSuccessfulLabel.setText("Pet Successfully Revived!");

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                .addGap(0, 158, Short.MAX_VALUE)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gameSave2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gameSave1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gameSave3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                        .addComponent(reviveSuccessfulLabel)
                        .addGap(395, 395, 395))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(139, 139, 139))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(399, 399, 399))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(gameSave1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(gameSave2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(gameSave3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(reviveSuccessfulLabel)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        getContentPane().add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.setName("background"); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1280, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        parentalControlsHomeScreen nextScreen = new parentalControlsHomeScreen(manager);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                petRevivalScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_backButtonMouseClicked

    private void gameSave1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameSave1ButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        reviveSuccessfulLabel.setVisible(manager.revivePet(1));
    }//GEN-LAST:event_gameSave1ButtonMouseClicked

    private void gameSave2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameSave2ButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        reviveSuccessfulLabel.setVisible(manager.revivePet(2));
    }//GEN-LAST:event_gameSave2ButtonMouseClicked

    private void gameSave3ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameSave3ButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        reviveSuccessfulLabel.setVisible(manager.revivePet(3));
    }//GEN-LAST:event_gameSave3ButtonMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backButton;
    private javax.swing.JLabel backButtonLabel;
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel background;
    private javax.swing.JPanel border;
    private javax.swing.JPanel gameSave1Button;
    private javax.swing.JLabel gameSave1Label;
    private javax.swing.JPanel gameSave2Button;
    private javax.swing.JLabel gameSave2Label;
    private javax.swing.JPanel gameSave3Button;
    private javax.swing.JLabel gameSave3Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel reviveSuccessfulLabel;
    // End of variables declaration//GEN-END:variables
}
