
package forms;
import classes.*;

import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import java.util.Timer;
import java.util.TimerTask;


public class petTypeScreen extends javax.swing.JFrame {
    private String selectedPet;
    private saveManager manager;
    private int saveSlot;


    public petTypeScreen() {
        initComponents();

    }

    public petTypeScreen(saveManager manager, int saveSlot) {
        initComponents();
        this.manager = manager;
        this.saveSlot = saveSlot;

        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escapePressed");
        this.getRootPane().getActionMap().put("escapePressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                exitMainMenuMouseClicked(null);
            }
        });

        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_1, 0), "pufferfishPressed");
        this.getRootPane().getActionMap().put("pufferfishPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pufferfishButtonMouseClicked(null);
            }
        });

        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_2, 0), "axolotlPressed");
        this.getRootPane().getActionMap().put("axolotlPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                axolotlButtonMouseClicked(null);
            }
        });

        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_3, 0), "sharkPressed");
        this.getRootPane().getActionMap().put("sharkPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                sharkButtonMouseClicked(null);
            }
        });

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        border = new javax.swing.JPanel();
        exitFrame = new javax.swing.JPanel();
        exitMainMenu = new javax.swing.JLabel();
        pufferfishButton = new javax.swing.JPanel();
        pufferfishText = new javax.swing.JLabel();
        petPreviewText = new javax.swing.JLabel();
        axolotlButton = new javax.swing.JPanel();
        axolotlText = new javax.swing.JLabel();
        sharkButton = new javax.swing.JPanel();
        sharkText = new javax.swing.JLabel();
        pufferfishPickImage = new javax.swing.JLabel();
        axolotlPickImage = new javax.swing.JLabel();
        sharkPickImage = new javax.swing.JLabel();
        backgroundEffects = new forms.backgroundEffects();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        border.setBackground(new java.awt.Color(204, 204, 204));
        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        border.setName("border"); // NOI18N
        border.setOpaque(false);

        exitFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        exitFrame.setPreferredSize(new java.awt.Dimension(72, 32));

        exitMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitButton.png"))); // NOI18N
        exitMainMenu.setName("exitMainMenu"); // NOI18N
        exitMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exitFrameLayout = new javax.swing.GroupLayout(exitFrame);
        exitFrame.setLayout(exitFrameLayout);
        exitFrameLayout.setHorizontalGroup(
                exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(exitMainMenu)
        );
        exitFrameLayout.setVerticalGroup(
                exitFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(exitMainMenu)
        );

        pufferfishButton.setBackground(new java.awt.Color(229, 145, 214));
        pufferfishButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        pufferfishButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pufferfishButton.setPreferredSize(new java.awt.Dimension(160, 60));
        pufferfishButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pufferfishButtonMouseClicked(evt);
            }
        });

        pufferfishText.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        pufferfishText.setForeground(new java.awt.Color(255, 255, 255));
        pufferfishText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pufferfishText.setText("Pufferfish");
        pufferfishText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pufferfishText.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout pufferfishButtonLayout = new javax.swing.GroupLayout(pufferfishButton);
        pufferfishButton.setLayout(pufferfishButtonLayout);
        pufferfishButtonLayout.setHorizontalGroup(
                pufferfishButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pufferfishButtonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pufferfishText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pufferfishButtonLayout.setVerticalGroup(
                pufferfishButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pufferfishButtonLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pufferfishText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        petPreviewText.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        petPreviewText.setForeground(new java.awt.Color(255, 255, 255));
        petPreviewText.setText("Select Pet Type ");

        axolotlButton.setBackground(new java.awt.Color(229, 145, 214));
        axolotlButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        axolotlButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        axolotlButton.setPreferredSize(new java.awt.Dimension(160, 60));
        axolotlButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                axolotlButtonMouseClicked(evt);
            }
        });

        axolotlText.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        axolotlText.setForeground(new java.awt.Color(255, 255, 255));
        axolotlText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        axolotlText.setText("Axolotl");
        axolotlText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        axolotlText.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout axolotlButtonLayout = new javax.swing.GroupLayout(axolotlButton);
        axolotlButton.setLayout(axolotlButtonLayout);
        axolotlButtonLayout.setHorizontalGroup(
                axolotlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(axolotlButtonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(axolotlText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        axolotlButtonLayout.setVerticalGroup(
                axolotlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, axolotlButtonLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(axolotlText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        sharkButton.setBackground(new java.awt.Color(229, 145, 214));
        sharkButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 96, 164), 4));
        sharkButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sharkButton.setPreferredSize(new java.awt.Dimension(160, 60));
        sharkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sharkButtonMouseClicked(evt);
            }
        });

        sharkText.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        sharkText.setForeground(new java.awt.Color(255, 255, 255));
        sharkText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sharkText.setText("Shark");
        sharkText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sharkText.setPreferredSize(new java.awt.Dimension(160, 60));

        javax.swing.GroupLayout sharkButtonLayout = new javax.swing.GroupLayout(sharkButton);
        sharkButton.setLayout(sharkButtonLayout);
        sharkButtonLayout.setHorizontalGroup(
                sharkButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sharkButtonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sharkText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sharkButtonLayout.setVerticalGroup(
                sharkButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sharkButtonLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sharkText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pufferfishPickImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pufferfish5.png"))); // NOI18N
        pufferfishPickImage.setText("jLabel1");

        axolotlPickImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sharkPreview.png"))); // NOI18N

        sharkPickImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/axolotlPick-01.png"))); // NOI18N

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
                borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(borderLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(375, 375, 375)
                                .addComponent(petPreviewText)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(borderLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pufferfishPickImage, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pufferfishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addComponent(axolotlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sharkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(axolotlPickImage))
                                .addGap(41, 41, 41))
                        .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                                        .addContainerGap(497, Short.MAX_VALUE)
                                        .addComponent(sharkPickImage)
                                        .addGap(478, 478, 478)))
        );
        borderLayout.setVerticalGroup(
                borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(borderLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(exitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(borderLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(petPreviewText)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(borderLayout.createSequentialGroup()
                                                .addComponent(pufferfishPickImage)
                                                .addGap(110, 110, 110)
                                                .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pufferfishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(axolotlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(sharkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(axolotlPickImage, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53))
                        .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                                        .addContainerGap(259, Short.MAX_VALUE)
                                        .addComponent(sharkPickImage)
                                        .addGap(239, 239, 239)))
        );

        getContentPane().add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
        getContentPane().add(backgroundEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.setName("background"); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void exitMainMenuMouseClicked(java.awt.event.MouseEvent evt) {
        SoundManager.playSound("sound/button_click.wav");
        newGameGUI nextScreen = new newGameGUI(manager);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                petTypeScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }

    private void pufferfishButtonMouseClicked(java.awt.event.MouseEvent evt) {
        SoundManager.playSound("sound/button_click.wav");
        petPreviewScreen nextScreen = new petPreviewScreen(manager, "pufferfish", saveSlot);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                petTypeScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }

    private void axolotlButtonMouseClicked(java.awt.event.MouseEvent evt) {
        SoundManager.playSound("sound/button_click.wav");
        petPreviewScreen nextScreen = new petPreviewScreen(manager, "axolotl", saveSlot);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                petTypeScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }

    private void sharkButtonMouseClicked(java.awt.event.MouseEvent evt) {
        SoundManager.playSound("sound/button_click.wav");
        petPreviewScreen nextScreen = new petPreviewScreen(manager, "shark", saveSlot);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                petTypeScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }



    // Variables declaration - do not modify
    private javax.swing.JPanel axolotlButton;
    private javax.swing.JLabel axolotlPickImage;
    private javax.swing.JLabel axolotlText;
    private javax.swing.JLabel background;
    private forms.backgroundEffects backgroundEffects;
    private javax.swing.JPanel border;
    private javax.swing.JPanel exitFrame;
    private javax.swing.JLabel exitMainMenu;
    private javax.swing.JPanel newAxolotlButton;
    private javax.swing.JPanel newAxolotlButton1;
    private javax.swing.JPanel newPufferfishButton;
    private javax.swing.JPanel newPufferfishButton1;
    private javax.swing.JPanel newPufferfishButton2;
    private javax.swing.JLabel petPreviewText;
    private javax.swing.JPanel pufferfishButton;
    private javax.swing.JLabel pufferfishPickImage;
    private javax.swing.JLabel pufferfishText;
    private javax.swing.JLabel selectAxolotlText;
    private javax.swing.JLabel selectAxolotlText1;
    private javax.swing.JLabel selectPufferfishText;
    private javax.swing.JLabel selectPufferfishText1;
    private javax.swing.JLabel selectPufferfishText2;
    private javax.swing.JPanel sharkButton;
    private javax.swing.JLabel sharkPickImage;
    private javax.swing.JLabel sharkText;
    // End of variables declaration
}
