
package forms;
import java.util.Timer;
import java.util.TimerTask;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;

import classes.SoundManager;
import classes.saveManager;
import classes.parentalControls;

public class playerStatsScreen extends javax.swing.JFrame {
    private saveManager manager;
    private parentalControls gameParentControls;
    /**
     * Creates new form mainGameScreen
     */
    public playerStatsScreen() {
        initComponents();
    }

    public playerStatsScreen(saveManager manager) {
        initComponents();
        this.manager = manager;
        this.gameParentControls = manager.PCReader();

        // Set statistics
        String[] stats = gameParentControls.displayStatistics();
        totalPlayLabel.setText(totalPlayLabel.getText() + " " + stats[0] + " h");
        averagePlayLabel.setText(averagePlayLabel.getText() + " " + stats[1] + " h");

        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escapePressed");
        this.getRootPane().getActionMap().put("escapePressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                backButtonMouseClicked(null);
            }
        });

        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_R, 0), "resetPressed");
        this.getRootPane().getActionMap().put("resetPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                resetStatsButtonActionPerformed(null);
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border = new javax.swing.JPanel();
        backPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalPlayLabel = new javax.swing.JLabel();
        averagePlayLabel = new javax.swing.JLabel();
        resetStatsButton = new javax.swing.JButton();
        backButton = new javax.swing.JPanel();
        backButtonLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        border.setBackground(new java.awt.Color(204, 204, 204));
        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        border.setName("border"); // NOI18N
        border.setOpaque(false);

        backPanel.setBackground(new java.awt.Color(229, 145, 214));
        backPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(179, 96, 164), 4, true));
        backPanel.setPreferredSize(new java.awt.Dimension(1100, 550));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Player Statistics");

        totalPlayLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalPlayLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalPlayLabel.setText("Total Playtime:");

        averagePlayLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        averagePlayLabel.setForeground(new java.awt.Color(255, 255, 255));
        averagePlayLabel.setText("Average Playtime Per Session:");

        resetStatsButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resetStatsButton.setForeground(new java.awt.Color(229, 145, 214));
        resetStatsButton.setText("Reset Statistics");
        resetStatsButton.setPreferredSize(new java.awt.Dimension(220, 50));
        resetStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetStatsButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setForeground(new java.awt.Color(229, 145, 214));
        backButton.setPreferredSize(new java.awt.Dimension(220, 47));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        backButtonLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backButtonLabel.setForeground(new java.awt.Color(229, 145, 214));
        backButtonLabel.setText("Back");

        javax.swing.GroupLayout backButtonLayout = new javax.swing.GroupLayout(backButton);
        backButton.setLayout(backButtonLayout);
        backButtonLayout.setHorizontalGroup(
            backButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(backButtonLabel)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        backButtonLayout.setVerticalGroup(
            backButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(backButtonLabel)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(434, 434, 434))
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(averagePlayLabel)
                            .addComponent(totalPlayLabel)
                            .addComponent(jLabel1)))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(totalPlayLabel)
                .addGap(36, 36, 36)
                .addComponent(averagePlayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(resetStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        getContentPane().add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.setName("background"); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1280, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void resetStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetStatsButtonActionPerformed
        SoundManager.playSound("sound/button_click.wav");
        gameParentControls.resetTimeLog();

        // Re-display stats
        String[] stats = gameParentControls.displayStatistics();
        totalPlayLabel.setText("Total Playtime: " + stats[0] + " h");
        averagePlayLabel.setText("Average Playtime Per Session " + stats[1] + " h");
    }//GEN-LAST:event_resetStatsButtonActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        SoundManager.playSound("sound/button_click.wav");
        parentalControlsHomeScreen nextScreen = new parentalControlsHomeScreen(manager);
        nextScreen.setVisible(true);
        Timer switchTimer = new Timer();
        TimerTask closeCurrent = new TimerTask() {
            @Override
            public void run() {
                playerStatsScreen.this.dispose();
                switchTimer.cancel();
            }
        };
        switchTimer.schedule(closeCurrent, 3000);
    }//GEN-LAST:event_backButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averagePlayLabel;
    private javax.swing.JPanel backButton;
    private javax.swing.JLabel backButtonLabel;
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel background;
    private javax.swing.JPanel border;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resetStatsButton;
    private javax.swing.JLabel totalPlayLabel;
    // End of variables declaration//GEN-END:variables
}
